// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2023-2025 Matti Tiainen <mvtiaine@cc.hut.fi>

//> using dep org.scala-lang.modules::scala-parallel-collections::1.2.0

import scala.collection.mutable.Buffer
import scala.collection.parallel.CollectionConverters._
import scala.util.Using

import convert._

enum Source:
  case
    NONE,
    _17Bit5thDimension,
    _17BitCollection,
    _17BitContinuation,
    _17BitLevel6,
    _17BitPhaseFour,
    _1996Mods,
    _500MBNyheder1,
    _500MBNyheder2,
    _500MBNyheder3,
    _500MBNyheder4,
    _500MBNyheder5,
    _500MBNyheder6,
    _500MBNyheder7,
    _500MBNyheder8,
    _500MBNyheder11,
    _9000Sounds,
    AB20,
    ACCUG,
    ACE1,
    ACE2,
    ACE3,
    ACE4,
    ActorSoundGraphics,
    AdventuresInHeaven,
    AlmatheraCDPD1,
    AlmatheraCDPD2,
    AlmatheraCDTVDemoCol1,
    AlmatheraCDTVDemoCol2,
    AlteredPerception,
    AmbMod,
    Amegas,
    AmigaAktuell,
    AmigaFDInside,
    AmigaMuseum,
    AmigaMegaDemos,
    AmigaMegaGames,
    AmigaModulesFreeFr,
    AmigaMusicCollection,
    AmigaNuts,
    AmigaScne,
    AmigaTools1,
    AmigaTools2,
    AmigaTools3,
    AmigaTools4,
    AmigaTools5,
    AmigaTools6,
    Aminet,
    AmiSectorOne,
    AMOSPDCD,
    AMP,
    AOLFileLibrary,
    APDL2,
    ArcadeBBS,
    ArcadeDemonCoUK,
    ArtPacksAcidOrg,
    ArtScene,
    Assassins1,
    Assassins2,
    Assassins3,
    Assassins4,
    AtariForever1,
    AtariForever2,
    AtariFTP,
    AtariMegaArchive1,
    AtariMegaArchive2,
    Audio494,
    AudioMIDI,
    BCINET1,
    BCINET2,
    BestOfSelectMM3,
    BestOfSelectMM4,
    BestOfSelectMM5,
    BestOfSelectMM6,
    BestOfSelectMM15,
    BestOfSelectMM20,
    BlasterSoundBBS,
    BostonII,
    CDExchange,
    CDPlayer6,
    CDROMAktiv5,
    CDWareMultimedia3,
    CelicModules,
    CEUSOnline,
    ChillProductions,
    ChipSpecialSoundMidi,
    ChiptuneApp,
    ChiptuneCom,
    ClassicGameSoundtracks,
    ClubAmigaDeMontreal,
    CreativeComputers1,
    Dacapo,
    DaJormas,
    DatafilePDCD1b,
    DatafilePDCD2,
    DatafilePDCD3,
    DatafilePDCD4,
    Deck,
    Demodulate,
    DemonHellraiser,
    DemozooMusicLeftovers,
    DemozooProdLeftovers,
    DerMediaPlexSampler,
    DfxCollection,
    DieMultimediaPower,
    DigitalSymphony,
    Dim13,
    DrMusic,
    DrMusicLab,
    DynamicMusicStation,
    ElysianArchive,
    EMPhase4,
    EpicCollection1,
    EpicCollection3,
    EqualizerBBS,
    EspritDeAppleCorps,
    EuroCD3,
    EuroScene1,
    EuroScene2,
    Explossion3,
    ExpressPdGalore,
    F1Licenseware,
    Falcon030Power1,
    Falcon030Power2,
    FishNMore1,
    FishNMore2,
    FishNMore3,
    Flerp,
    Floppyshop3,
    Floppyshop4,
    Floppyshop6,
    Floppyshop7,
    FloppyshopSelect,
    FredTheGang2014,
    FreedomCD,
    FrenchStorm,
    FTPKloszArtPL,
    Fujiology,
    Funet,
    FunNGames2,
    FunNGames4,
    FunNGames9,
    FunNGames10,
    FunNGames13,
    FunNGames14,
    FunNGames15,
    FunNGames19,
    FunNGames20,
    FunNGames21,
    FunNGames30,
    GigaPDv2,
    GigaPDv3,
    GrandSlam1,
    GrandSlam3,
    GroovyBytes,
    HackedAmigaMusic,
    HackerChronicles2,
    Haxorfi,
    Hobbes,
    Hornet,
    HorrorSensation,
    HotScenestuff,
    HotShareware1,
    HotShareware17,
    HotShareware18,
    HotShareware34,
    HotShareware35,
    HotShareware36,
    HotShareware38,
    HotSoundVision,
    HotSoundVision2,
    Hottest4,
    Hottest5,
    Hottest6,
    ImphobiaDreams,
    ImphobiaDreams2,
    InformaticaMultimedia196,
    InsideShareware296,
    JBB,
    jPVSceneReleases,
    KeygenMusicPack202003,
    KoopOokPCConsument,
    Kosmic,
    LazarusAmigaDecade,
    LearningCurve,
    LeisureGamePak,
    LeisureGamePak2,
    LemonAmiga,
    LSDCompendium1,
    LSDCompendium2,
    LSDCompendium3,
    MACD1,
    MACD2,
    MACD3,
    MACD4,
    MACD5,
    MACD6,
    MACD7,
    MACD8,
    MACD9,
    MACD10,
    MACD11,
    MajaRadio,
    MassiveModCollection,
    MasterOfMusic,
    MaximumMods,
    MAXSounds,
    MazziveInjection97,
    MazziveInjection98,
    MazziveInjection2k,
    MBnet,
    MediaShare8,
    MegaAV,
    MegaDemo1,
    MegaGames1,
    Megahits1,
    Megahits2,
    Megahits3,
    Megahits4,
    Megahits6,
    Megahits7,
    MegaModMadness,
    MegaROM1,
    MegaROM2,
    MegaROM3,
    Megashare2,
    Megaware19,
    MetinSeven,
    Melcom,
    MidiMultimediaExchangeBBS,
    MidiWaveWorkShop,
    MillenniumGold2000,
    Minerva2,
    Minerva3,
    Minerva4,
    Mission1,
    Mission3,
    Mod4Win,
    ModJP,
    ModArchive,
    Modiromppu,
    Modland,
    ModlandFavourites,
    ModlandIncoming,
    ModlandSoftware,
    ModPlanet,
    ModSoulBrother,
    ModsAnthology,
    ModulesInJP,
    ModulesPL,
    ModulyPL,
    MonkeyGrafikSound,
    Monstro,
    MrGreat,
    MrOherd,
    MSDOSWorld2,
    MultimediaClassic,
    MultimediaExplosion,
    MultiMediaEXPLOSIONShareware,
    MultimediaGalerie,
    MultimediaLaCompil2,
    MultiMediaMegahits1,
    MultimediaMusicbox,
    MultimediaPlus,
    MultimediaSoundFactory,
    MultimediaToolkitPS,
    Music95,
    MusicBox1994,
    MusicBoxPC,
    MusicModSoundEffect,
    MusicWin952,
    NetlabelArchive,
    NetworkCD1,
    NetworkCD2,
    Newsflash1,
    Newsflash2,
    NightshiftSoundVision,
    NoiseMusic,
    NostalgicPlayer,
    Octamed6,
    OctaMEDSSv1,
    OldExotica,
    Otherware,
    PCConsument2Mar95,
    PCMagazineCover,
    PDShareware14000,
    Perseus,
    Phoenix3,
    Phoenix4,
    Phoenix5,
    PlayItByYear,
    Plex1,
    Plex2,
    Plex3,
    Plex4,
    Plex5,
    Plex6,
    PowerModul1,
    PowerModul2,
    PowerOn,
    PrimaShareware3,
    ProTrackerModulesGPack,
    RatsNest,
    RedHotShareware93,
    ResourceLibMultimedia,
    RetroExo,
    RetroPlayWHDLoadPacks,
    RusBBSArchive,
    ScenaPLEXE,
    Scene96,
    SceneCat,
    SceneOrg,
    SceneOrgLostFound,
    SceneReleases8095,
    SceneSporg,
    SceneStorm,
    SceneXplorer,
    SceneXplorer2,
    SciFiSensationv2,
    Sembiance,
    SharewareExtravaganza,
    SharewareUniverseGold,
    SightsSounds,
    SOAMC,
    Software2000,
    SoftwareExplosion,
    SoMuchShareware1,
    SoMuchShareware2,
    SoMuchShareware3,
    SoMuchShareware5,
    SonixCD,
    Sound1,
    Soundblaster17,
    SoundblasterMultiMedia3,
    SoundblasterMultiMedia4,
    SoundCollection,
    SoundMod1,
    SoundMod2,
    SoundMusicMidiCollection2,
    Sounds1996,
    SoundSoftware,
    SoundsTerrific,
    SoundsTerrificII,
    SoundStudio,
    SoundwareCollection,
    SPACELib1,
    StarportBBS,
    SXIIIKeygenMusic,
    TCDGameMods,
    TCEDemo2,
    TEKNO51996,
    TEKNO61996,
    TEKNO11997,
    TEKNO41997,
    TEKNO1998MusicMania,
    TerraSoundLibrary,
    TerryGreenPD,
    TheBBSOrgArchive,
    TheDarkCornerBBS,
    TheModuleCollection,
    TheSceneArchives,
    TheSoundLibrary,
    TheSoundSite,
    TheUltimateModCollection,
    TheUltimateMusicSound1,
    TheUltimateMusicSound2,
    ToolsUnlimitedBlanker,
    TOSECMusic,
    TOSECMusicUnknown,
    Tundrah,
    UgamodCollection1,
    UgamodCollection2,
    Ultrasounds,
    UnExotica,
    UnitedPDGold,
    UniversInteractif,
    UtilitiesPro1500,
    VGASpectrum,
    VGASpectrum2,
    Vrtulnik1,
    Vrtulnik2,
    Vrtulnik3,
    WantedTeam,
    WantedTeamDATTapes,
    WeirdScienceMultimedia,
    WeirdScienceMultimedia2,
    WhitelineTransmission,
    WorkbenchAddOn,
    WorldOfA1200,
    WorldOfAmiga,
    WorldOfGameMods,
    WorldOfShareware,
    WorldOfSound1,
    WorldOfSound2,
    Zakalwe,
    Unnamed

import Source._

import scala.deriving.*

final case class Constraint (
  path: String = "",
  _type: String = "",
  _platform: String = "",
  year: Int = 0
)
type C = Constraint
val C = Constraint

lazy val sourceConstraints: Map[Source, Seq[C]] = Map(
  _17Bit5thDimension -> Seq(C(_platform = "Amiga", year = 1995)),
  _17BitCollection -> Seq(C(_platform = "Amiga", year = 1993)),
  _17BitContinuation -> Seq(C(_platform = "Amiga", year = 1993)),
  _17BitLevel6 -> Seq(C(_platform = "Amiga", year = 1998)),
  _17BitPhaseFour -> Seq(C(_platform = "Amiga", year = 1994)),
  _1996Mods -> Seq(C(year = 1997)),
  _500MBNyheder1 -> Seq(C(year = 1995)),
  _500MBNyheder2 -> Seq(C(year = 1995)),
  _500MBNyheder3 -> Seq(C(year = 1995)),
  _500MBNyheder4 -> Seq(C(year = 1995)),
  _500MBNyheder5 -> Seq(C(year = 1995)),
  _500MBNyheder6 -> Seq(C(year = 1995)),
  _500MBNyheder7 -> Seq(C(year = 1995)),
  _500MBNyheder8 -> Seq(C(year = 1996)),
  _500MBNyheder11 -> Seq(C(year = 1996)),
  _9000Sounds -> Seq(C(year = 1993)),
  AB20 -> Seq(C(_platform = "Amiga", year = 1992)),
  ACCUG -> Seq(C(_platform = "Amiga", year = 1997)),
  ACE1 -> Seq(
    C(path = "DEMO/", _type = "Demo", _platform = "PC", year = 1994),
    C(path = "DISKMAG/", _type = "Mag", _platform = "PC", year = 1994),
    C(path = "INTRO/", _type = "Intro", _platform = "PC", year = 1994),
    C(path = "ZIKDISK/", _type = "MusicDisk", _platform = "PC", year = 1994),
    C(year = 1994)
  ),
  ACE2 -> Seq(
    C(path = "CD/DEMOMAGS/", _type = "Mag", _platform = "PC", year = 1995),
    C(path = "CD/DEMOS/", _type = "Demo", _platform = "PC", year = 1995),
    C(path = "CD/INTROS/", _type = "Intro", _platform = "PC", year = 1995),
    C(path = "CD/INVITS/", _type = "Invitation", _platform = "PC", year = 1995),
    C(path = "CD/MUSICDSK/", _type = "MusicDisk", _platform = "PC", year = 1995),
    C(year = 1995)
  ),
  ACE3 -> Seq(
    C(path = "1/demos/", _type = "Demo", _platform = "PC", year = 1996),
    C(path = "1/intros/", _type = "Intro", _platform = "PC", year = 1996),
    C(path = "1/mags/", _type = "Mag", _platform = "PC", year = 1996),
    C(path = "2/MUSICDIS/", _type = "MusicDisk", _platform = "PC", year = 1996),
    C(year = 1996)
  ),
  ACE4 -> Seq(
    C(path = "1/DEMOS/", _type = "Demo", _platform = "PC", year = 1997),
    C(path = "1/INTROS/", _type = "Intro", _platform = "PC", year = 1997),
    C(path = "1/MAGS/", _type = "Mag", _platform = "PC", year = 1997),
    C(path = "1/MUSICDIS/", _type = "MusicDisk", _platform = "PC", year = 1997),
    C(path = "2/INVITS/", _type = "Invitation", _platform = "PC", year = 1997),
    C(year = 1997)
  ),
  ActorSoundGraphics -> Seq(C(year = 1994)),
  AdventuresInHeaven -> Seq(C(year = 1993)),
  AlmatheraCDPD1 -> Seq(C(_platform = "Amiga", year = 1992)),
  AlmatheraCDPD2 -> Seq(C(_platform = "Amiga", year = 1992)),
  AlmatheraCDTVDemoCol1 -> Seq(C(_platform = "Amiga", year = 1992)),
  AlmatheraCDTVDemoCol2 -> Seq(C(_platform = "Amiga", year = 1993)),
  AlteredPerception -> Seq(C(year = 2000)),
  AmbMod -> Seq(C(year = 2000)),
  Amegas -> Seq(C(_platform = "Amiga")),
  AmigaAktuell -> Seq(C(year = 1996)),
  AmigaFDInside -> Seq(C(year = 1995)),
  AmigaMuseum -> Seq(C(_type = "Game", _platform = "Amiga", year = 2004)),
  AmigaMegaDemos -> Seq(C(_type = "Demo", _platform = "Amiga")), // TODO not really only demos?
  AmigaMegaGames -> Seq(C(_type = "Game", _platform = "Amiga")),
  // AmigaModulesFreeFr
  AmigaMusicCollection -> Seq(C(year = 2010)),
  AmigaNuts -> Seq(C(year = 1992)),
  AmigaScne -> Seq(
    C(path = "Parties/"),
    C(_type = "Demo", _platform = "Amiga")
  ),
  AmigaTools1 -> Seq(C(year = 1994)),
  AmigaTools2 -> Seq(C(year = 1995)),
  AmigaTools3 -> Seq(C(year = 1995)),
  AmigaTools4 -> Seq(C(year = 1996)),
  AmigaTools5 -> Seq(C(year = 1996)),
  AmigaTools6 -> Seq(C(year = 1997)),
  Aminet -> Seq(
    C(path = "demo/funet/Euroscene"), // duplicates Euroscene* sources
    C(path = "game/", _type = "Game", _platform = "Amiga"),
    C(path = "demo/", _type = "Demo", _platform = "Amiga"),
    C(path = "mags/", _type = "Mag", _platform = "Amiga")
  ),
  AmiSectorOne -> Seq(
    C(path = "demos/", _type = "Demo", _platform = "Amiga", year = 2001),
    C(path = "emerald/", _type = "Game", _platform = "Amiga", year = 2001),
    C(path = "games/", _type = "Game", _platform = "Amiga", year = 2001),
    C(path = "lsd-docs/", _type = "Mag", _platform = "Amiga", year = 2001),
    C(_platform = "Amiga", year = 2001)
  ),
  AMOSPDCD -> Seq(C(_platform = "Amiga", year = 1994)),
  // AMP
  AOLFileLibrary -> Seq(C(year = 2014)),
  APDL2 -> Seq(C(year = 1996)),
  ArcadeBBS -> Seq(C(year = 1996)),
  ArcadeDemonCoUK -> Seq(C(year = 2013)),
  ArtPacksAcidOrg -> Seq(C(year = 2004)),
  // ArtScene
  Assassins1 -> Seq(C(year = 1994)),
  Assassins2 -> Seq(C(year = 1995)),
  Assassins3 -> Seq(C(year = 1997)),
  Assassins4 -> Seq(C(year = 1999)),
  AtariForever1 -> Seq(C(year = 1996)),
  AtariForever2 -> Seq(C(year = 1996)),
  AtariFTP -> Seq(C(year = 1993)),
  AtariMegaArchive1 -> Seq(C(year = 1994)),
  AtariMegaArchive2 -> Seq(C(year = 1995)),
  Audio494 -> Seq(C(year = 1994)),
  AudioMIDI -> Seq(C(year = 1998)),
  BCINET1 -> Seq(C(year = 1994)),
  BCINET2 -> Seq(C(year = 1995)),
  BestOfSelectMM3 -> Seq(C(year = 1995)),
  BestOfSelectMM4 -> Seq(C(year = 1995)),
  BestOfSelectMM5 -> Seq(C(year = 1995)),
  BestOfSelectMM6 -> Seq(C(year = 1995)),
  BestOfSelectMM15 -> Seq(C(year = 1996)),
  BestOfSelectMM20 -> Seq(C(year = 1997)),
  BlasterSoundBBS -> Seq(C(year = 1997)),
  BostonII -> Seq(C(year = 1993)),
  CDExchange -> Seq(C(year = 1994)),
  CDPlayer6 -> Seq(C(year = 1995)),
  CDROMAktiv5 -> Seq(C(year = 1996)),
  CDWareMultimedia3 -> Seq(C(year = 1994)),
  CelicModules -> Seq(C(year = 1997)),
  CEUSOnline -> Seq(C(year = 1995)),
  // ChillProductions
  ChipSpecialSoundMidi -> Seq(C(year = 1993)),
  // ChiptuneApp
  // ChiptuneCom
  ClassicGameSoundtracks -> Seq(C(_platform = "Amiga")),
  ClubAmigaDeMontreal -> Seq(C(year = 1994)),
  CreativeComputers1 -> Seq(C(year = 1994)),
  Dacapo -> Seq(C(year = 1995)),
  DaJormas -> Seq(
    C(path = "productions/", _type = "Demo", _platform = "Amiga"),
    C(_platform = "Amiga")
  ),
  DatafilePDCD1b -> Seq(C(year = 1995)),
  DatafilePDCD2 -> Seq(C(year = 1994)),
  DatafilePDCD3 -> Seq(C(year = 1995)),
  DatafilePDCD4 -> Seq(C(year = 1996)),
  Deck -> Seq(C(path = "amiga", _platform = "Amiga")),
  Demodulate -> Seq(C(_type = "Demo", year = 2005)),
  DemonHellraiser -> Seq(C(_platform = "Amiga")),
  // DemozooMusicLeftovers
  // DemozooProdLeftovers
  DerMediaPlexSampler -> Seq(C(year = 1994)),
  DfxCollection -> Seq(
    C(path = "AmigaDemoCD", _type = "Demo", _platform = "Amiga", year = 2000),
    C(year = 2000)
  ),
  DieMultimediaPower -> Seq(C(year = 1993)),
  DigitalSymphony -> Seq(C(year = 1995)),
  // Dim13
  DrMusic -> Seq(
    C(path = "DEMOS/", _type = "Demo", _platform = "PC", year = 1993),
    C(year = 1993)
  ),
  DrMusicLab -> Seq(C(year = 1994)),
  DynamicMusicStation -> Seq(C(year = 1995)),
  ElysianArchive -> Seq(C(year = 1993)),
  EMPhase4 -> Seq(C(year = 1996)),
  EpicCollection1 -> Seq(C(year = 1996)),
  EpicCollection3 -> Seq(C(year = 1997)),
  EqualizerBBS -> Seq(C(year = 2004)),
  EspritDeAppleCorps -> Seq(C(year = 2001)),
  EuroCD3 -> Seq(C(year = 1998)),
  EuroScene1 -> Seq(
    C(path = "DEMOS/", _type = "Demo", _platform = "Amiga", year = 1994),
    C(path = "DISKMAGS/", _type = "Mag", _platform = "Amiga", year = 1994),
    C(year = 1994)
  ),
  EuroScene2 -> Seq(
    C(path = "DEMOS/", _type = "Demo", _platform = "Amiga", year = 1995),
    C(path = "DISKMAGS/", _type = "Mag", _platform = "Amiga", year = 1995),
    C(year = 1995)
  ),
  Explossion3 -> Seq(C(year = 1994)),
  ExpressPdGalore -> Seq(C(year = 1994)),
  F1Licenseware -> Seq(C(year = 1995)),
  Falcon030Power1 -> Seq(C(year = 1997)),
  Falcon030Power2 -> Seq(C(year = 1998)),
  FishNMore1 -> Seq(C(year = 1990)),
  FishNMore2 -> Seq(C(year = 1991)),
  FishNMore3 -> Seq(C(year = 1993)),
  Flerp -> Seq(C(year = 2002)),
  Floppyshop3 -> Seq(C(year = 1998)),
  Floppyshop4 -> Seq(C(year = 1998)),
  Floppyshop6 -> Seq(C(year = 1998)),
  Floppyshop7 -> Seq(C(year = 1998)),
  FloppyshopSelect -> Seq(C(year = 1998)),
  FredTheGang2014 -> Seq(C(year = 2014)), // TODO unclear if 2014 is actually correct because timestamps are not usable
  FreedomCD -> Seq(
    C(path = "DEMOS/", _type = "Demo", _platform = "PC", year = 1995),
    C(year = 1995)
  ),
  FrenchStorm -> Seq(C(year = 1996)),
  FTPKloszArtPL -> Seq(C(year = 2005)),
  Fujiology -> Seq(
    C(path = "FALCON/", _type = "Demo", _platform = "Atari"),
    C(path = "JAGUAR/", _type = "Demo", _platform = "Atari"),
    C(path = "ST/", _type = "Demo", _platform = "Atari"),
    C(path = "TT/", _type = "Demo", _platform = "Atari"),
    C(path = "MAGS/", _type = "Mag", _platform = "Atari")
  ),
  Funet -> Seq(
    C(path = "amiga/audio/modules/med/1992", year = 1992),
    C(path = "amiga/audio/modules/med/1993", year = 1993),
    C(path = "amiga/audio/modules/med/1994", year = 1994),
    C(path = "amiga/audio/modules/misc/1992/", year = 1992),
    C(path = "amiga/audio/modules/misc/1993/", year = 1993),
    C(path = "amiga/audio/modules/misc/1994/", year = 1994),
    C(path = "amiga/demos/diskmags/", _type = "Mag", _platform = "Amiga", year = 1999),
    C(path = "amiga/demos/games/", _type = "Game", _platform = "Amiga", year = 1999),
    C(path = "amiga/demos/PARTIES/", year = 1999),
    C(path = "amiga/demos/", _type = "Demo", _platform = "Amiga", year = 1999),
    C(path = "amiga/games/", _type = "Game", _platform = "Amiga", year = 1999),
    C(path = "amiga/", year = 1999),
    C(path = "atari/demo/", _type = "Demo", _platform = "Atari", year = 1999),
    C(path = "atari/game/", _type = "Game", _platform = "Atari", year = 1999),
    C(path = "atari/mag/", _type = "Mag", _platform = "Atari", year = 1999),
    C(path = "atari/falcon/demo/", _type = "Demo", _platform = "Atari", year = 1999),
    C(path = "atari/falcon/games/", _type = "Game", _platform = "Atari", year = 1999),
    C(path = "atari/falcon/mag/", _type = "Mag", _platform = "Atari", year = 1999),
    C(path = "atari/", year = 1999),
    C(path = "msdos/Simtel/", year = 2010),
    C(path = "msdos/games/", _type = "Game", _platform = "PC", year = 1999),
    C(path = "msdos/", year = 1999),
    C(year = 1999),
  ),
  FunNGames2 -> Seq(C(year = 1994)),
  FunNGames4 -> Seq(C(year = 1994)),
  FunNGames9 -> Seq(C(year = 1995)),
  FunNGames10 -> Seq(C(year = 1995)),
  FunNGames13 -> Seq(C(year = 1995)),
  FunNGames14 -> Seq(C(year = 1995)),
  FunNGames15 -> Seq(C(year = 1995)),
  FunNGames19 -> Seq(C(year = 1996)),
  FunNGames20 -> Seq(C(year = 1996)),
  FunNGames21 -> Seq(C(year = 1996)),
  FunNGames30 -> Seq(C(year = 1997)),
  GigaPDv2 -> Seq(C(year = 1993)),
  GigaPDv3 -> Seq(C(year = 1994)),
  GrandSlam1 -> Seq(C(year = 1994)),
  GrandSlam3 -> Seq(C(year = 1995)),
  GroovyBytes -> Seq(
    C(path = "DEMOS/", _type = "Demo", _platform = "PC", year = 1996),
    C(path = "DISKMAGS/", _type = "Mag", _platform = "PC", year = 1996),
    C(path = "MUSICDSK/", _type = "MusicDisk", _platform = "PC", year = 1996),
    C(year = 1996)
  ),
  HackedAmigaMusic -> Seq(
    C(path = "CrackTunes/", _type = "Cracktro", _platform = "Amiga", year = 2000),
    C(path = "mdls/", _type = "Game", _platform = "Amiga", year = 1995),
    C(path = "Rips/", _type = "Game", _platform = "Amiga", year = 1997),
    C(_platform = "Amiga", year = 2003),
  ),
  HackerChronicles2 -> Seq(C(year = 1994)),
  // Haxorfi
  Hobbes -> Seq(
    C(path = "os2/games/", _type = "Game", _platform = "PC"),
    C(path = "os2/", _platform = "PC"),
),
  Hornet -> Seq(
    C(path = "demos/", _type = "Demo", _platform = "PC", year = 1998),
    C(path = "mags/", _type = "Mag", _platform = "PC", year = 1998),
    C(path = "party/", _type = "Demo", _platform = "PC", year = 1998),
    C(year = 1998)
  ),
  HorrorSensation -> Seq(C(year = 1995)),
  HotScenestuff -> Seq(C(year = 1996)),
  HotShareware1 -> Seq(C(year = 1995)),
  HotShareware17 -> Seq(C(year = 1997)),
  HotShareware18 -> Seq(C(year = 1997)),
  HotShareware34 -> Seq(C(year = 1998)),
  HotShareware35 -> Seq(C(year = 1998)),
  HotShareware36 -> Seq(C(year = 1998)),
  HotShareware38 -> Seq(C(year = 1998)),
  HotSoundVision -> Seq(
    C(path = "HOTSV/DEMO/", _type = "Demo", _platform = "PC", year = 1993),
    C(year = 1993))
  ,
  HotSoundVision2 -> Seq(
    C(path = "HOTSV2/DEMO/MUSIC/", _type = "MusicDisk", year = 1994),
    C(path = "HOTSV2/DEMO/", _type = "Demo", _platform = "PC", year = 1994),
    C(year = 1994)
  ),
  Hottest4 -> Seq(C(year = 1994)),
  Hottest5 -> Seq(C(year = 1995)),
  Hottest6 -> Seq(C(year = 1996)),
  ImphobiaDreams -> Seq(
    C(path = "CD/DEMOS/", _type = "Demo", _platform = "PC", year = 1996),
    C(path = "CD/DISKMAGS/", _type = "Mag", _platform = "PC", year = 1996),
    C(path = "CD/INTROS/", _type = "Intro", _platform = "PC", year = 1996),
    C(path = "CD/REPORTS/", _type = "Report", _platform = "PC", year = 1996),
    C(path = "CD/MUSIC/DISKS/", _type = "MusicDisk", _platform = "PC", year = 1996),
    C(year = 1996)
  ),
  ImphobiaDreams2 -> Seq(
    C(path = "1/CD1/DEMOS/", _type = "Demo", _platform = "PC", year = 1998),
    C(path = "1/CD1/DISKMAGS/", _type = "Mag", _platform = "PC", year = 1998),
    C(path = "1/CD1/INTROS/", _type = "Intro", _platform = "PC", year = 1998),
    C(path = "1/CD1/REPORTS/", _type = "Report", _platform = "PC", year = 1998),
    C(path = "2/CD2/MUSIC/DISKS/", _type = "MusicDisk", _platform = "PC", year = 1998),
    C(year = 1998)
  ),
  InformaticaMultimedia196 -> Seq(C(year = 1995)),
  InsideShareware296 -> Seq(C(year = 1996)),
  JBB -> Seq(C(_platform = "Amiga", year = 2000)),
  jPVSceneReleases -> Seq(
    C(path = "2001/", _type = "Demo", _platform = "Amiga", year = 2001),
    C(path = "2002/", _type = "Demo", _platform = "Amiga", year = 2002),
    C(path = "2003/", _type = "Demo", _platform = "Amiga", year = 2003),
    C(path = "2004/", _type = "Demo", _platform = "Amiga", year = 2004),
    C(path = "2005/", _type = "Demo", _platform = "Amiga", year = 2005),
    C(path = "2006/", _type = "Demo", _platform = "Amiga", year = 2006),
    C(path = "2007/", _type = "Demo", _platform = "Amiga", year = 2007),
    C(path = "2008/", _type = "Demo", _platform = "Amiga", year = 2008),
    C(path = "2009/", _type = "Demo", _platform = "Amiga", year = 2009),
    C(path = "2010/", _type = "Demo", _platform = "Amiga", year = 2010),
    C(path = "2011/", _type = "Demo", _platform = "Amiga", year = 2011),
    C(path = "2012/", _type = "Demo", _platform = "Amiga", year = 2012),
    C(path = "2013/", _type = "Demo", _platform = "Amiga", year = 2013),
    C(path = "2014/", _type = "Demo", _platform = "Amiga", year = 2014),
    C(path = "2015/", _type = "Demo", _platform = "Amiga", year = 2015),
    C(path = "2016/", _type = "Demo", _platform = "Amiga", year = 2016),
    C(path = "2017/", _type = "Demo", _platform = "Amiga", year = 2017),
    C(path = "2018/", _type = "Demo", _platform = "Amiga", year = 2018),
    C(path = "2019/", _type = "Demo", _platform = "Amiga", year = 2019),
    C(path = "2020/", _type = "Demo", _platform = "Amiga", year = 2020),
    C(path = "2024/", _type = "Demo", _platform = "Amiga", year = 2024),
    C(path = "Unlisted_stuff/2001", _type = "Demo", _platform = "Amiga", year = 2001),
    C(path = "Unlisted_stuff/2002", _type = "Demo", _platform = "Amiga", year = 2002),
    C(path = "Unlisted_stuff/2003", _type = "Demo", _platform = "Amiga", year = 2003),
    C(path = "Unlisted_stuff/2004", _type = "Demo", _platform = "Amiga", year = 2004),
    C(path = "Unlisted_stuff/2005", _type = "Demo", _platform = "Amiga", year = 2005),
    C(path = "Unlisted_stuff/2006", _type = "Demo", _platform = "Amiga", year = 2006),
    C(path = "Unlisted_stuff/2007", _type = "Demo", _platform = "Amiga", year = 2007),
    C(path = "Unlisted_stuff/2008", _type = "Demo", _platform = "Amiga", year = 2008),
    C(path = "Unlisted_stuff/2009", _type = "Demo", _platform = "Amiga", year = 2009),
    C(path = "Unlisted_stuff/2010", _type = "Demo", _platform = "Amiga", year = 2010),
    C(path = "Unlisted_stuff/2011", _type = "Demo", _platform = "Amiga", year = 2011),
    C(path = "Unlisted_stuff/2012", _type = "Demo", _platform = "Amiga", year = 2012),
    C(path = "Unlisted_stuff/2013", _type = "Demo", _platform = "Amiga", year = 2013),
    C(path = "Unlisted_stuff/2014", _type = "Demo", _platform = "Amiga", year = 2014),
    C(path = "Unlisted_stuff/2015", _type = "Demo", _platform = "Amiga", year = 2015),
    C(path = "Unlisted_stuff/2016", _type = "Demo", _platform = "Amiga", year = 2016),
    C(path = "Unlisted_stuff/2017", _type = "Demo", _platform = "Amiga", year = 2017),
    C(path = "Unlisted_stuff/2018", _type = "Demo", _platform = "Amiga", year = 2018),
    C(path = "Unlisted_stuff/2019", _type = "Demo", _platform = "Amiga", year = 2019),
    C(path = "Unlisted_stuff/2020", _type = "Demo", _platform = "Amiga", year = 2020),
    C( _type = "Demo", _platform = "Amiga", year = 2024)
  ),
  // KeygenMusicPack202003
  KoopOokPCConsument -> Seq(C(year = 1994)),
  Kosmic -> Seq(
    C(path = "1996/", year = 1996),
    C(path = "1997/", year = 1997),
    C(path = "1998/", year = 1998),
    C(path = "1999/", year = 1999),
    C(path = "2000/", year = 2000),
    C(path = "mdisks/", _type = "MusicDisk", _platform = "PC", year = 2000),
    C(year = 2000)
  ),
  LazarusAmigaDecade -> Seq(
    C(path = "1/Demos/", _type = "Demo", _platform = "Amiga", year = 2011),
    C(path = "1/Games/", _type = "Game", _platform = "Amiga", year = 2011),
    C(path = "2/Games/", _type = "Game", _platform = "Amiga", year = 2011),
    C(year = 2011)
  ),
  LearningCurve -> Seq(C(year = 1996)),
  LeisureGamePak -> Seq(C(year = 1994)),
  LeisureGamePak2 -> Seq(C(year = 1995)),
  LemonAmiga -> Seq(
    C(path = "1987/", _platform = "Amiga", year = 1988),
    C(path = "Cracktro/", _type = "Cracktro", _platform = "Amiga", year = 2020),
    C(path = "Demos/", _type = "Demo", _platform = "Amiga", year = 2020),
    C(path = "GAMES/", _type = "Game", _platform = "Amiga", year = 2020),
    C(path = "LSD-Grapevine --/", _type = "Mag", _platform = "Amiga", year = 1995),
    C(year = 2020)
  ),
  LSDCompendium1 -> Seq(C(year = 1994)),
  LSDCompendium2 -> Seq(C(year = 1995)),
  LSDCompendium3 -> Seq(C(year = 1995)),
  MACD1 -> Seq(C(year = 1997)),
  MACD2 -> Seq(C(year = 1997)),
  MACD3 -> Seq(C(year = 1997)),
  MACD4 -> Seq(C(year = 1997)),
  MACD5 -> Seq(C(year = 1997)),
  MACD6 -> Seq(C(year = 1998)),
  MACD7 -> Seq(C(year = 1998)),
  MACD8 -> Seq(C(year = 1998)),
  MACD9 -> Seq(C(year = 1998)),
  MACD10 -> Seq(C(year = 1999)),
  MACD11 -> Seq(C(year = 1999)),
  // MajaRadio
  MassiveModCollection -> Seq(C(year = 1995)),
  MasterOfMusic -> Seq(C(year = 1996)),
  MaximumMods -> Seq(C(year = 1996)),
  MAXSounds -> Seq(C(year = 1995)),
  MazziveInjection97 -> Seq(C(year = 1997)),
  MazziveInjection98 -> Seq(C(year = 1998)),
  MazziveInjection2k -> Seq(C(year = 2000)),
  MBnet -> Seq(C(year = 2002)),
  MediaShare8 -> Seq(C(year = 1994)),
  MegaAV -> Seq(C(year = 1992)),
  MegaDemo1 -> Seq(C(year = 1992)),
  MegaGames1 -> Seq(C(year = 1993)),
  Megahits1 -> Seq(C(year = 1994)),
  Megahits2 -> Seq(C(year = 1994)),
  Megahits3 -> Seq(C(year = 1994)),
  Megahits4 -> Seq(C(year = 1994)),
  Megahits6 -> Seq(C(year = 1995)),
  Megahits7 -> Seq(C(year = 1996)),
  MegaModMadness -> Seq(C(year = 1994)),
  MegaROM1 -> Seq(C(year = 1992)),
  MegaROM2 -> Seq(C(year = 1992)),
  MegaROM3 -> Seq(C(year = 1993)),
  Megashare2 -> Seq(C(year = 1994)),
  Megaware19 -> Seq(C(year = 1994)),
  Melcom -> Seq(C(year = 2005)),
  MetinSeven -> Seq(C(_platform = "Amiga", year = 1999)),
  MidiMultimediaExchangeBBS -> Seq(C(year = 1993)),
  MidiWaveWorkShop -> Seq(C(year = 1993)),
  MillenniumGold2000 -> Seq(C(year = 1999)),
  Minerva2 -> Seq(C(year = 1992)),
  Minerva3 -> Seq(C(year = 1993)),
  Minerva4 -> Seq(C(year = 1993)),
  Mission1 -> Seq(C(year = 1995)),
  Mission3 -> Seq(C(year = 1999)),
  Mod4Win -> Seq(C(year = 1996)),
  ModJP -> Seq(C(year = 2001)),
  ModArchive -> Seq(
    C(path = "modarchive_2007", year = 2007),
    C(path = "modarchive_2008", year = 2008),
    C(path = "modarchive_2009", year = 2009),
    C(path = "modarchive_2010", year = 2010),
    C(path = "modarchive_2011", year = 2011),
    C(path = "modarchive_2012", year = 2012),
    C(path = "modarchive_2013", year = 2013),
    C(path = "modarchive_2014", year = 2014),
    C(path = "modarchive_2015", year = 2015),
    C(path = "modarchive_2016", year = 2016),
    C(path = "modarchive_2017", year = 2017),
    C(path = "modarchive_2018", year = 2018),
    C(path = "modarchive_2019", year = 2019),
    C(path = "modarchive_2020", year = 2020),
    C(path = "modarchive_2021", year = 2021),
    C(path = "modarchive_2022", year = 2022),
    C(path = "modarchive_2023", year = 2023),
    C(path = "modarchive_2024", year = 2024),
    C(path = "modarchive_2025", year = 2025),
    C(year = 2025)
  ),
  Modiromppu -> Seq(
    C(path = "DEMOS/", _type = "Demo", _platform = "PC", year = 1998),
    C(path = "MUSICDSK", _type = "MusicDisk", _platform = "PC", year = 1998),
    C(year = 1998)
  ),
  // Modland,
  // ModlandFavourites
  // ModlandIncoming
  // ModlandSoftware
  ModPlanet -> Seq(
    C(path = "cd2/demodulate/amiga demos/", _type = "Demo", _platform = "Amiga", year = 2002),
    C(path = "cd2/demodulate/amiga diskmags/", _type = "Mag", _platform = "Amiga", year = 2002),
    C(path = "cd2/demodulate/amiga intros/", _type = "Intro", _platform = "Amiga", year = 2002),
    C(path = "cd2/demodulate/pc demos/", _type = "Demo", _platform = "PC", year = 2002),
    C(path = "cd2/demodulate/pc diskmags/", _type = "Mag", _platform = "PC", year = 2002),
    C(path = "cd2/demodulate/pc intros/", _type = "Intro", _platform = "PC", year = 2002),
    C(path = "cd2/music disks/amiga/", _type = "MusicDisk", _platform = "Amiga", year = 2002),
    C(path = "cd2/music disks/pc/", _type = "MusicDisk", _platform = "PC", year = 2002),
    C(path = "bonuscd/demodulate/amiga intros/", _type = "Intro", _platform = "Amiga", year = 2006),
    C(path = "bonuscd/demodulate/pc demos/", _type = "Demo", _platform = "PC", year = 2006),
    C(path = "bonuscd/demodulate/pc intros/", _type = "Intro", _platform = "PC", year = 2006),
    C(path = "cd1/", year = 2002),
    C(path = "cd2/", year = 2002),
    C(path = "bonuscd/", year = 2006),
    C(year = 2006)
  ),
  ModSoulBrother -> Seq(C(year = 2005)),
  ModsAnthology -> Seq(C(year = 1996)),
  ModulesInJP -> Seq(C(year = 2003)),
  // ModulesPL
  ModulyPL -> Seq(C(year = 2007)),
  MonkeyGrafikSound -> Seq(C(year = 1994)),
  Monstro -> Seq(C(year = 2002)),
  MrOherd -> Seq(C(year = 2020)),
  // MrGreat
  MSDOSWorld2 -> Seq(C(year = 1995)),
  MultimediaClassic -> Seq(C(year = 1995)),
  MultimediaExplosion -> Seq(C(year = 1994)),
  MultiMediaEXPLOSIONShareware -> Seq(C(year = 1993)),
  MultimediaGalerie -> Seq(C(year = 1993)),
  MultimediaLaCompil2 -> Seq(C(year = 1995)),
  MultiMediaMegahits1 -> Seq(C(year = 1994)),
  MultimediaMusicbox -> Seq(C(year = 1994)),
  MultimediaPlus -> Seq(C(year = 1994)),
  MultimediaSoundFactory -> Seq(C(year = 1995)),
  MultimediaToolkitPS -> Seq(C(year = 1994)),
  Music95 -> Seq(C(year = 1997)),
  MusicBox1994 -> Seq(C(year = 1993)),
  MusicBoxPC -> Seq(C(year = 1995)),
  MusicModSoundEffect -> Seq(C(year = 1995)),
  MusicWin952 -> Seq(C(year = 1998)),
  // NetlabelArchive
  NetworkCD1 -> Seq(C(year = 1994)),
  NetworkCD2 -> Seq(C(year = 1995)),
  Newsflash1 -> Seq(C(year = 1994)),
  Newsflash2 -> Seq(C(year = 1994)),
  NightshiftSoundVision -> Seq(C(year = 1995)),
  NoiseMusic -> Seq(
    C(path = "1995/", year = 1995),
    C(path = "1996/", year = 1996),
    C(path = "1997/", year = 1997),
    C(path = "1998/", year = 1998),
    C(path = "1999/", year = 1999),
    C(path = "2000", year = 2000),
    C(year = 2002)
  ),
  // NostalgicPlayer
  Octamed6 -> Seq(C(year = 1995)),
  OctaMEDSSv1 -> Seq(C(year = 1996)),
  OldExotica -> Seq(C(_platform = "Amiga", year = 2007)),
  Otherware -> Seq(C(year = 1993)),
  PCConsument2Mar95 -> Seq(C(year = 1995)),
  PCMagazineCover -> Seq(C(year = 2000)),
  PDShareware14000 -> Seq(C(year = 1992)),
  Perseus -> Seq(C(year = 1994)),
  Phoenix3 -> Seq(C(year = 1992)),
  Phoenix4 -> Seq(C(year = 1993)),
  Phoenix5 -> Seq(C(year = 1994)),
  PlayItByYear -> Seq(
    // a bit unreliable years
    C(path = "1985", _type = "Game", _platform = "Amiga", year = 1985+1),
    C(path = "1986", _type = "Game", _platform = "Amiga", year = 1986+1),
    C(path = "1987", _type = "Game", _platform = "Amiga", year = 1987+1),
    C(path = "1988", _type = "Game", _platform = "Amiga", year = 1988+1),
    C(path = "1989", _type = "Game", _platform = "Amiga", year = 1989+1),
    C(path = "1990", _type = "Game", _platform = "Amiga", year = 1990+1),
    C(path = "1991", _type = "Game", _platform = "Amiga", year = 1991+1),
    C(path = "1992", _type = "Game", _platform = "Amiga", year = 1992+1),
    C(path = "1993", _type = "Game", _platform = "Amiga", year = 1993+1),
    C(path = "1994", _type = "Game", _platform = "Amiga", year = 1994+1),
    C(path = "1995", _type = "Game", _platform = "Amiga", year = 1995+1),
    C(path = "85-91.zip/85-91.hdf/1985", _type = "Game", _platform = "Amiga", year = 1985+1),
    C(path = "85-91.zip/85-91.hdf/1986", _type = "Game", _platform = "Amiga", year = 1986+1),
    C(path = "85-91.zip/85-91.hdf/1987", _type = "Game", _platform = "Amiga", year = 1987+1),
    C(path = "85-91.zip/85-91.hdf/1988", _type = "Game", _platform = "Amiga", year = 1988+1),
    C(path = "85-91.zip/85-91.hdf/1989", _type = "Game", _platform = "Amiga", year = 1989+1),
    C(path = "85-91.zip/85-91.hdf/1990", _type = "Game", _platform = "Amiga", year = 1990+1),
    C(path = "85-91.zip/85-91.hdf/199１", _type = "Game", _platform = "Amiga", year = 1991+1),
    C(path = "92-95.zip/92-95.hdf/1992", _type = "Game", _platform = "Amiga", year = 1992+1),
    C(path = "92-95.zip/92-95.hdf/1993", _type = "Game", _platform = "Amiga", year = 1993+1),
    C(path = "92-95.zip/92-95.hdf/1994", _type = "Game", _platform = "Amiga", year = 1994+1),
    C(path = "92-95.zip/92-95.hdf/1995", _type = "Game", _platform = "Amiga", year = 1995+1),
    C(_type = "Game", _platform = "Amiga")
  ),
  Plex1 -> Seq(C(year = 1995)),
  Plex2 -> Seq(C(year = 1994)),
  Plex3 -> Seq(C(year = 1994)),
  Plex4 -> Seq(C(year = 1994)),
  Plex5 -> Seq(C(year = 1994)),
  Plex6 -> Seq(C(year = 1995)),
  PowerModul1 -> Seq(C(year = 1995)),
  PowerModul2 -> Seq(C(year = 1995)),
  PowerOn -> Seq(C(year = 1994)),
  PrimaShareware3 -> Seq(C(year = 1998)),
  // ProTrackerModulesGPack
  RatsNest -> Seq(C(year = 1997)),
  RedHotShareware93 -> Seq(C(year = 1993)),
  ResourceLibMultimedia -> Seq(C(year = 1993)),
  RetroExo -> Seq(
    C(path = "exodemoscene/", _type = "Demo", _platform = "PC", year = 2023),
    C(path = "exowin9x/1994/", _type = "Game", _platform = "PC", year = 1994),
    C(path = "exowin9x/1995/", _type = "Game", _platform = "PC", year = 1995),
    C(path = "exowin9x/1996/", _type = "Game", _platform = "PC", year = 1996),
    C(path = "exowin3x/", _type = "Game", _platform = "PC", year = 2001),
    C(_platform = "PC")
  ),
  RetroPlayWHDLoadPacks -> Seq(
    C(path = "Commodore_Amiga_-_HD_Loaders_-_Games", _type = "Game", _platform = "Amiga"),
    C(path = "Commodore_Amiga_-_JST_-_Games", _type = "Game", _platform = "Amiga"),
    C(path = "Commodore_Amiga_-_WHDLoad_-_Demos", _type = "Demo", _platform = "Amiga"),
    C(path = "Commodore_Amiga_-_WHDLoad_-_Games", _type = "Game", _platform = "Amiga"),
    C(path = "Commodore_Amiga_-_WHDLoad_-_Magazines", _type = "Mag", _platform = "Amiga"),
    C(_platform = "Amiga")
  ),
  RusBBSArchive -> Seq(C(year = 2000)),
  ScenaPLEXE -> Seq(C(year = 1995)),
  Scene96 -> Seq(
    C(path = "1/DEMOS/", _type = "Demo", _platform = "PC", year = 1997),
    C(path = "1/DISKMAGS/", _type = "Mag", _platform = "PC", year = 1997),
    C(path = "1/GAMES/", _type = "Game", _platform = "PC", year = 1997),
    C(path = "1/INTROS/", _type = "Intro", _platform = "PC", year = 1997),
    C(path = "1/PARTY/INVTROS/", _type = "Invitation", _platform = "PC", year = 1997),
    C(path = "1/PARTY/REPORTS/", _type = "Report", _platform = "PC", year = 1997),
    C(path = "2/MUSICDSK/", _type = "MusicDisk", _platform = "PC", year = 1997),
    C(year = 1997)
  ),
  SceneCat -> Seq(
    C(path = "Demotunez/", _type = "Demo"),
    C(path = "games/", _type = "Game"),
    C(path = "SceneCAT_Select/game/", _type = "Game"),
    C(path = "SceneCAT_Select/Various_BestofAmigaGameMusic/", _type = "Game", _platform = "Amiga"),
  ),
  SceneOrg -> Seq(
    C(path = "demos/", _type = "Demo"),
    C(path = "mags/", _type = "Mag"),
    C(path = "music/disks/", _type = "MusicDisk"),
    C(path = "parties/1987", year = 1987),
    C(path = "parties/1988", year = 1988),
    C(path = "parties/1989", year = 1989),
    C(path = "parties/1990", year = 1990),
    C(path = "parties/1991", year = 1991),
    C(path = "parties/1992", year = 1992),
    C(path = "parties/1993", year = 1993),
    C(path = "parties/1994/theparty94/misc/the_party_94_cdrom", year = 1995),
    C(path = "parties/1994", year = 1994),
    C(path = "parties/1995", year = 1995),
    C(path = "parties/1996", year = 1996),
    C(path = "parties/1997", year = 1997),
    C(path = "parties/1998", year = 1998),
    C(path = "parties/1999", year = 1999),
    C(path = "parties/2000", year = 2000),
    C(path = "parties/2001", year = 2001),
    C(path = "parties/2002", year = 2002),
    C(path = "parties/2003", year = 2003),
    C(path = "parties/2004", year = 2004),
    C(path = "parties/2005", year = 2005),
    C(path = "parties/2006", year = 2006),
    C(path = "parties/2007", year = 2007),
    C(path = "parties/2008", year = 2008),
    C(path = "parties/2009", year = 2009),
    C(path = "parties/2010", year = 2010),
    C(path = "parties/2011", year = 2011),
    C(path = "parties/2012", year = 2012),
    C(path = "parties/2013", year = 2013),
    C(path = "parties/2014", year = 2014),
    C(path = "parties/2015", year = 2015),
    C(path = "parties/2016", year = 2016),
    C(path = "parties/2017", year = 2017),
    C(path = "parties/2018", year = 2018),
    C(path = "parties/2019", year = 2019),
    C(path = "parties/2020", year = 2020),
    C(path = "parties/2021", year = 2021),
    C(path = "parties/2022", year = 2022),
    C(path = "parties/2023", year = 2023),
    C(path = "parties/2024", year = 2024),
    C(path = "parties/2025", year = 2025),
    C(path = "parties/2026", year = 2026)
  ),
  // SceneOrgLostFound
  SceneReleases8095 -> Seq(
    C(path = "1980/", _type = "Game", _platform = "PC", year = 1989),
    C(path = "1990/", _type = "Game", _platform = "PC", year = 1990),
    C(path = "1991/", _type = "Game", _platform = "PC", year = 1991),
    C(path = "1992/", _type = "Game", _platform = "PC", year = 1992),
    C(path = "1993/", _type = "Game", _platform = "PC", year = 1993),
    C(path = "1994/", _type = "Game", _platform = "PC", year = 1994),
    C(path = "1995/", _type = "Game", _platform = "PC", year = 1995),
  ),
  SceneSporg -> Seq(
    C(path = "1994/", year = 1994),
    C(path = "1995/", year = 1995),
    C(path = "1997/", year = 1997),
    C(path = "2001/", year = 2001),
    C(path = "2002/", year = 2002),
    C(path = "2003/", year = 2003),
    C(path = "2004/", year = 2004),
    C(path = "2005/", year = 2005),
    C(path = "2006/", year = 2006),
    C(path = "2007/", year = 2007),
    C(path = "diskmags/", _type = "Mag", year = 2010),
    C(year = 2010)
  ),
  SceneStorm -> Seq(
    C(path = "Charts&Diskmags", _type = "Mag", _platform = "Amiga", year = 1997),
    C(path = "Demos/", _type = "Demo", _platform = "Amiga", year = 1997),
    C(path = "Intros/", _type = "Intro", _platform = "Amiga", year = 1997),
    C(path = "Music-Disks/", _type = "MusicDisk", _platform = "Amiga", year = 1997),
    C(path = "Slideshows/", _type = "SlideShow", _platform = "Amiga", year = 1997),
    C(year = 1997)
  ),
  SceneXplorer -> Seq(
    C(path = "!DEMOS!/", _type = "Demo", _platform = "Amiga", year = 1997),
    C(path = "!GRAPHICS!/Slideshows/", _type = "SlideShow", _platform = "Amiga", year = 1997),
    C(path = "!INTROS!/", _type = "Intro", _platform = "Amiga", year = 1997),
    C(path = "!MAGAZINES_&_PACKS/", _type = "Mag", _platform = "Amiga", year = 1997),
    C(path = "!MUSIC!/Music_disks/", _type = "MusicDisk", _platform = "Amiga", year = 1997),
    C(year = 1997)
  ),
  SceneXplorer2 -> Seq(
    C(path = "!DEMOS!/", _type = "Demo", _platform = "Amiga", year = 1998),
    C(path = "!GRAPHICS!/Slideshows/", _type = "SlideShow", _platform = "Amiga", year = 1998),
    C(path = "!INTROS!/", _type = "Intro", _platform = "Amiga", year = 1998),
    C(path = "!MAGS^PACKS!/", _type = "Mag", _platform = "Amiga", year = 1998),
    C(path = "!MUSIC!/Music_disks/", _type = "MusicDisk", _platform = "Amiga", year = 1998),
    C(year = 1998)
  ),
  SciFiSensationv2 -> Seq(C(year = 1996)),
  // Sembiance
  SharewareExtravaganza -> Seq(C(year = 1993)),
  SharewareUniverseGold -> Seq(C(year = 1996)),
  SightsSounds -> Seq(C(year = 1993)),
  SOAMC -> Seq(
    C(path = "000/AMIGA/Trackers_Games/", _type = "Game", _platform = "Amiga", year = 2021),
    C(year = 2021)
  ),
  Software2000 -> Seq(C(year = 1995)),
  SoftwareExplosion -> Seq(C(year = 1996)),
  SoMuchShareware1 -> Seq(C(year = 1991)),
  SoMuchShareware2 -> Seq(C(year = 1993)),
  SoMuchShareware3 -> Seq(C(year = 1993)),
  SoMuchShareware5 -> Seq(C(year = 1995)),
  SonixCD -> Seq(C(_platform = "Amiga", year = 1989)),
  Sound1 -> Seq(C(year = 1995)),
  Soundblaster17 -> Seq(C(year = 1995)),
  SoundblasterMultiMedia3 -> Seq(C(year = 1994)),
  SoundblasterMultiMedia4 -> Seq(C(year = 1994)),
  SoundCollection -> Seq(C(year = 1995)),
  SoundMod1 -> Seq(C(year = 1994)),
  SoundMod2 -> Seq(C(year = 1995)),
  SoundMusicMidiCollection2 -> Seq(C(year = 1996)),
  Sounds1996 -> Seq(C(year = 1996)),
  SoundSoftware -> Seq(C(year = 1996)),
  SoundsTerrific -> Seq(C(year = 1994)),
  SoundsTerrificII -> Seq(C(year = 1996)),
  SoundStudio -> Seq(C(year = 1995)),
  SoundwareCollection -> Seq(C(year = 1993)),
  SPACELib1 -> Seq(C(year = 1993)),
  StarportBBS -> Seq(C(year = 1999)),
  // SXIIIKeygenMusic
  TCDGameMods -> Seq(C(_platform = "Amiga")),
  TCEDemo2 -> Seq(C(year = 1997)),
  TEKNO51996 -> Seq(C(year = 1996)),
  TEKNO61996 -> Seq(C(year = 1996)),
  TEKNO11997 -> Seq(C(year = 1996)),
  TEKNO41997 -> Seq(C(year = 1997)),
  TEKNO1998MusicMania -> Seq(C(year = 1998)),
  TerraSoundLibrary -> Seq(
    C(path = "DEMO/", _type = "Demo", _platform = "Amiga", year = 1995),
    C(year = 1995)
  ),
  TerryGreenPD -> Seq(
    C(path = "art/", _platform = "Amiga", year = 2006),
    C(path = "demos/", _type = "Demo", _platform = "Amiga", year = 2006),
    C(path = "games/", _type = "Game", _platform = "Amiga", year = 2006),
    C(path = "utils/", _platform = "Amiga", year = 2006),
    C(year = 2006)
  ),
  TheBBSOrgArchive -> Seq(C(year = 2022)),
  TheDarkCornerBBS -> Seq(
    C(path = "Demo/", _type = "Demo", _platform = "PC", year = 2001),
    C(path = "Games/", _type = "Game", _platform = "PC", year = 2001),
    C(year = 2001)
  ),
  TheModuleCollection -> Seq(C(year = 1995)),
  TheSceneArchives -> Seq(C(_platform = "Amiga", year = 2002)),
  // TheSoundLibrary
  TheSoundSite -> Seq(C(year = 1993)),
  TheUltimateModCollection -> Seq(C(year = 1992)),
  TheUltimateMusicSound1 -> Seq(
    C(path = "MUS_DISK/", _type = "MusicDisk", _platform = "PC", year = 1995),
    C(year = 1995)
  ),
  TheUltimateMusicSound2 -> Seq(
    C(path = "MUS_DISK/", _type = "MusicDisk", _platform = "PC", year = 1996),
    C(year = 1996)
  ),
  ToolsUnlimitedBlanker -> Seq(C(year = 1996)),
  TOSECMusic -> Seq(
    C(path = "Demos/", _type = "Demo", year = 2005),
    C(path = "Games/", _type = "Game", year = 2005),
    C(year = 2005)
  ),
  TOSECMusicUnknown -> Seq(
    C(path = "Music - Demos/", _type = "Demo", year = 2004),
    C(path = "Music - Games/", _type = "Game", year = 2004),
    C(year = 2004)
  ),
  Tundrah -> Seq(C(year = 2006)),
  UgamodCollection1 -> Seq(C(year = 1994)),
  UgamodCollection2 -> Seq(C(year = 1994)),
  Ultrasounds -> Seq(C(year = 1995)),
  UnExotica -> Seq(
    C(path = "Demo/", _type = "Demo", _platform = "Amiga", year = 2020),
    C(path = "Game/", _type = "Game", _platform = "Amiga", year = 2020),
    C(_platform = "Amiga", year = 2020)
  ),
  UnitedPDGold -> Seq(C(year = 1995)),
  UniversInteractif -> Seq(C(year = 1995)),
  Unnamed -> Seq(
    C(path = "Amiga_Cracktros_Modules", _type = "Cracktro", _platform = "Amiga"),
    C(path = "Amiga_GameMusic", _platform = "Amiga"),  // has also non-game music
    C(path = "Amiga_Games_Modules", _type = "Game", _platform = "Amiga"),
    C(path = "Amiga.Music", _type = "Game", _platform = "Amiga"),
    C(path = "Other Amiga Music.7z/Games/", _type = "Game", _platform = "Amiga")
    //C(_platform = "Amiga")
  ),
  UtilitiesPro1500 -> Seq(C(year = 1994)),
  VGASpectrum -> Seq(C(year = 1991)),
  VGASpectrum2 -> Seq(C(year = 1992)),
  Vrtulnik1 -> Seq(C(year = 1995)),
  Vrtulnik2 -> Seq(C(year = 1995)),
  Vrtulnik3 -> Seq(C(year = 1997)),
  WantedTeam -> Seq(
    C(path = "games/", _type = "Game", _platform = "Amiga", year = 2015),
    C(_platform = "Amiga", year = 2015)
  ),
  WantedTeamDATTapes -> Seq(
    C(path = "A1200Games", _type = "Game", _platform = "Amiga"),
    C(path = "CD32Games", _type = "Game", _platform = "Amiga"),
    C(path = "demos", _type = "Demo", _platform = "Amiga"),
    C(path = "games", _type = "Game", _platform = "Amiga"),
    C(path = "utils", _platform = "Amiga"),
    C(path = "wantedteam", _platform = "Amiga")
  ),
  WeirdScienceMultimedia -> Seq(C(year = 1993)),
  WeirdScienceMultimedia2 -> Seq(C(year = 1995)),
  WhitelineTransmission -> Seq(C(year = 1995)),
  WorkbenchAddOn -> Seq(C(year = 1995)),
  WorldOfA1200 -> Seq(C(year = 1995)),
  WorldOfAmiga -> Seq(C(year = 1995)),
  // WorldOfGameMods // has also Game remixes/covers etc.
  WorldOfShareware -> Seq(C(year = 1993)),
  WorldOfSound1 -> Seq(C(year = 1994)),
  WorldOfSound2 -> Seq(C(year = 1996)),
  Zakalwe -> Seq(
    C(path = "benn_daglish_sid/"),
    C(path = "mod/"),
    C(path = "pokeynoise/"),
    C(path = "quartet_psg", _platform = "Atari"),
    C(path = "quartet_st", _platform = "Atari"),
    C(path = "special_fx_st", _type = "Game", _platform = "Atari"),
    C(path = "tfmx_st", _type = "Game", _platform = "Atari"),
    C(_platform = "Amiga")
  )
)

val tsvfiles = Buffer(
  ("bbs/arcadebbs.tsv", ArcadeBBS),
  ("bbs/blastersoundbbs.tsv", BlasterSoundBBS),
  ("bbs/equalizerbbs.tsv", EqualizerBBS),
  ("bbs/mbnet.tsv", MBnet),
  ("bbs/midimultimediaexchangebbs.tsv", MidiMultimediaExchangeBBS),
  ("bbs/ratsnest.tsv", RatsNest),
  ("bbs/rusbbsarchive.tsv", RusBBSArchive),
  ("bbs/starportbbs.tsv", StarportBBS),
  ("bbs/thedarkcornerbbs.tsv", TheDarkCornerBBS),
  ("cd/17bit5thdimension.tsv", _17Bit5thDimension),
  ("cd/17bitcollection.tsv", _17BitCollection),
  ("cd/17bitcontinuation.tsv", _17BitContinuation),
  ("cd/17bitlevel6.tsv", _17BitLevel6),
  ("cd/17bitphasefour.tsv", _17BitPhaseFour),
  ("cd/500mbnyheder1.tsv", _500MBNyheder1),
  ("cd/500mbnyheder2.tsv", _500MBNyheder2),
  ("cd/500mbnyheder3.tsv", _500MBNyheder3),
  ("cd/500mbnyheder4.tsv", _500MBNyheder4),
  ("cd/500mbnyheder5.tsv", _500MBNyheder5),
  ("cd/500mbnyheder6.tsv", _500MBNyheder6),
  ("cd/500mbnyheder7.tsv", _500MBNyheder7),
  ("cd/500mbnyheder8.tsv", _500MBNyheder8),
  ("cd/500mbnyheder11.tsv", _500MBNyheder11),
  ("cd/9000sounds.tsv", _9000Sounds),
  ("cd/ab20.tsv", AB20),
  ("cd/ace1.tsv", ACE1),
  ("cd/ace2.tsv", ACE2),
  ("cd/ace3.tsv", ACE3),
  ("cd/ace4.tsv", ACE4),
  ("cd/actorsoundgraphics.tsv", ActorSoundGraphics),
  ("cd/adventuresinheaven.tsv", AdventuresInHeaven),
  ("cd/almatheracdpd1.tsv", AlmatheraCDPD1),
  ("cd/almatheracdpd2.tsv", AlmatheraCDPD2),
  ("cd/almatheracdtvdemocol1.tsv", AlmatheraCDTVDemoCol1),
  ("cd/almatheracdtvdemocol2.tsv", AlmatheraCDTVDemoCol2),
  ("cd/amigaaktuell.tsv", AmigaAktuell),
  ("cd/amigafdinside.tsv", AmigaFDInside),
  ("cd/amigatools1.tsv", AmigaTools1),
  ("cd/amigatools2.tsv", AmigaTools2),
  ("cd/amigatools3.tsv", AmigaTools3),
  ("cd/amigatools4.tsv", AmigaTools4),
  ("cd/amigatools5.tsv", AmigaTools5),
  ("cd/amigatools6.tsv", AmigaTools6),
  ("cd/amospdcd.tsv", AMOSPDCD),
  ("cd/apdl2.tsv", APDL2),
  ("cd/assassins1.tsv", Assassins1),
  ("cd/assassins2.tsv", Assassins2),
  ("cd/assassins3.tsv", Assassins3),
  ("cd/assassins4.tsv", Assassins4),
  ("cd/atariforever1.tsv", AtariForever1),
  ("cd/atariforever2.tsv", AtariForever2),
  ("cd/atarimegaarchive1.tsv", AtariMegaArchive1),
  ("cd/atarimegaarchive2.tsv", AtariMegaArchive2),
  ("cd/audio494.tsv", Audio494),
  ("cd/audiomidi.tsv", AudioMIDI),
  ("cd/bcinet1.tsv", BCINET1),
  ("cd/bcinet2.tsv", BCINET2),
  ("cd/bestofselectmm3.tsv", BestOfSelectMM3),
  ("cd/bestofselectmm4.tsv", BestOfSelectMM4),
  ("cd/bestofselectmm5.tsv", BestOfSelectMM5),
  ("cd/bestofselectmm6.tsv", BestOfSelectMM6),
  ("cd/bestofselectmm15.tsv", BestOfSelectMM15),
  ("cd/bestofselectmm20.tsv", BestOfSelectMM20),
  ("cd/boston2.tsv", BostonII),
  ("cd/cdexchange.tsv", CDExchange),
  ("cd/cdplayer6.tsv", CDPlayer6),
  ("cd/cdromaktiv5.tsv", CDROMAktiv5),
  ("cd/cdwaremultimedia3.tsv", CDWareMultimedia3),
  ("cd/ceusonline.tsv", CEUSOnline),
  ("cd/chipspecialsoundmidi.tsv", ChipSpecialSoundMidi),
  ("cd/clubamigamontreal.tsv", ClubAmigaDeMontreal),
  ("cd/creativecomputers1.tsv", CreativeComputers1),
  ("cd/dacapo.tsv", Dacapo),
  ("cd/datafilepdcd1b.tsv", DatafilePDCD1b),
  ("cd/datafilepdcd2.tsv", DatafilePDCD2),
  ("cd/datafilepdcd3.tsv", DatafilePDCD3),
  ("cd/datafilepdcd4.tsv", DatafilePDCD4),
  ("cd/dermediaplexsampler.tsv", DerMediaPlexSampler),
  ("cd/diemultimediapower.tsv", DieMultimediaPower),
  ("cd/digitalsymphony.tsv", DigitalSymphony),
  ("cd/drmusic.tsv", DrMusic),
  ("cd/drmusiclab.tsv", DrMusicLab),
  ("cd/dynamicmusicstation.tsv", DynamicMusicStation),
  ("cd/elysianarchive.tsv", ElysianArchive),
  ("cd/emphase4.tsv", EMPhase4),
  ("cd/epiccollection1.tsv", EpicCollection1),
  ("cd/epiccollection3.tsv", EpicCollection3),
  ("cd/eurocd3.tsv", EuroCD3),
  ("cd/euroscene1.tsv", EuroScene1),
  ("cd/euroscene2.tsv", EuroScene2),
  ("cd/explossion3.tsv", Explossion3),
  ("cd/expresspdgalore.tsv", ExpressPdGalore),
  ("cd/f1licenseware.tsv", F1Licenseware),
  ("cd/falcon030power1.tsv", Falcon030Power1),
  ("cd/falcon030power2.tsv", Falcon030Power2),
  ("cd/fishnmore1.tsv", FishNMore1),
  ("cd/fishnmore2.tsv", FishNMore2),
  ("cd/fishnmore3.tsv", FishNMore3),
  ("cd/floppyshop3.tsv", Floppyshop3),
  ("cd/floppyshop4.tsv", Floppyshop4),
  ("cd/floppyshop6.tsv", Floppyshop6),
  ("cd/floppyshop7.tsv", Floppyshop7),
  ("cd/floppyshopselect.tsv", FloppyshopSelect),
  ("cd/freedomcd.tsv", FreedomCD),
  ("cd/frenchstorm.tsv", FrenchStorm),
  ("cd/funngames2.tsv", FunNGames2),
  ("cd/funngames4.tsv", FunNGames4),
  ("cd/funngames9.tsv", FunNGames9),
  ("cd/funngames10.tsv", FunNGames10),
  ("cd/funngames13.tsv", FunNGames13),
  ("cd/funngames14.tsv", FunNGames14),
  ("cd/funngames15.tsv", FunNGames15),
  ("cd/funngames19.tsv", FunNGames19),
  ("cd/funngames20.tsv", FunNGames20),
  ("cd/funngames21.tsv", FunNGames21),
  ("cd/funngames30.tsv", FunNGames30),
  ("cd/gigapdv2.tsv", GigaPDv2),
  ("cd/gigapdv3.tsv", GigaPDv3),
  ("cd/grandslam1.tsv", GrandSlam1),
  ("cd/grandslam3.tsv", GrandSlam3),
  ("cd/groovybytes.tsv", GroovyBytes),
  ("cd/hackerchronicles2.tsv", HackerChronicles2),
  ("cd/horrorsensation.tsv", HorrorSensation),
  ("cd/hotscenestuff.tsv", HotScenestuff),
  ("cd/hotshareware1.tsv", HotShareware1),
  ("cd/hotshareware17.tsv", HotShareware17),
  ("cd/hotshareware18.tsv", HotShareware18),
  ("cd/hotshareware34.tsv", HotShareware34),
  ("cd/hotshareware35.tsv", HotShareware35),
  ("cd/hotshareware36.tsv", HotShareware36),
  ("cd/hotshareware38.tsv", HotShareware38),
  ("cd/hotsoundvision.tsv", HotSoundVision),
  ("cd/hotsoundvision2.tsv", HotSoundVision2),
  ("cd/hottest4.tsv", Hottest4),
  ("cd/hottest5.tsv", Hottest5),
  ("cd/hottest6.tsv", Hottest6),
  ("cd/imphobiadreams.tsv", ImphobiaDreams),
  ("cd/imphobiadreams2.tsv", ImphobiaDreams2),
  ("cd/informaticamultimedia196.tsv", InformaticaMultimedia196),
  ("cd/insideshareware296.tsv", InsideShareware296),
  ("cd/koopookpcconsument.tsv", KoopOokPCConsument),
  ("cd/lazarusamigadecade.tsv", LazarusAmigaDecade),
  ("cd/learningcurve.tsv", LearningCurve),
  ("cd/leisuregamepak.tsv", LeisureGamePak),
  ("cd/leisuregamepak2.tsv", LeisureGamePak2),
  ("cd/lsdcompendium1.tsv", LSDCompendium1),
  ("cd/lsdcompendium2.tsv", LSDCompendium2),
  ("cd/lsdcompendium3.tsv", LSDCompendium3),
  ("cd/macd1.tsv", MACD1),
  ("cd/macd2.tsv", MACD2),
  ("cd/macd3.tsv", MACD3),
  ("cd/macd4.tsv", MACD4),
  ("cd/macd5.tsv", MACD5),
  ("cd/macd6.tsv", MACD6),
  ("cd/macd7.tsv", MACD7),
  ("cd/macd8.tsv", MACD8),
  ("cd/macd9.tsv", MACD9),
  ("cd/macd10.tsv", MACD10),
  ("cd/macd11.tsv", MACD11),
  ("cd/massivemodcollection.tsv", MassiveModCollection),
  ("cd/masterofmusic.tsv", MasterOfMusic),
  ("cd/maximummods.tsv", MaximumMods),
  ("cd/maxsounds.tsv", MAXSounds),
  ("cd/mazziveinjection97.tsv", MazziveInjection97),
  ("cd/mazziveinjection98.tsv", MazziveInjection98),
  ("cd/mazziveinjection2k.tsv", MazziveInjection2k),
  ("cd/mediashare8.tsv", MediaShare8),
  ("cd/megaav.tsv", MegaAV),
  ("cd/megademo1.tsv", MegaDemo1),
  ("cd/megagames1.tsv", MegaGames1),
  ("cd/megahits1.tsv", Megahits1),
  ("cd/megahits2.tsv", Megahits2),
  ("cd/megahits3.tsv", Megahits3),
  ("cd/megahits4.tsv", Megahits4),
  ("cd/megahits6.tsv", Megahits6),
  ("cd/megahits7.tsv", Megahits7),
  ("cd/megamodmadness.tsv", MegaModMadness),
  ("cd/megarom1.tsv", MegaROM1),
  ("cd/megarom2.tsv", MegaROM2),
  ("cd/megarom3.tsv", MegaROM3),
  ("cd/megashare2.tsv", Megashare2),
  ("cd/megaware19.tsv", Megaware19),
  ("cd/midiwaveworkshop.tsv", MidiWaveWorkShop),
  ("cd/millenniumgold2000.tsv", MillenniumGold2000),
  ("cd/minerva2.tsv", Minerva2),
  ("cd/minerva3.tsv", Minerva3),
  ("cd/minerva4.tsv", Minerva4),
  ("cd/mission1.tsv", Mission1),
  ("cd/mission3.tsv", Mission3),
  ("cd/mod4win.tsv", Mod4Win),
  ("cd/modiromppu.tsv", Modiromppu),
  ("cd/modplanet.tsv", ModPlanet),
  ("cd/modsanthology.tsv", ModsAnthology),
  ("cd/monkeygrafiksound.tsv", MonkeyGrafikSound),
  ("cd/monstro.tsv", Monstro),
  ("cd/msdosworld2.tsv", MSDOSWorld2),
  ("cd/multimediaclassic.tsv", MultimediaClassic),
  ("cd/multimediaexplosion.tsv", MultimediaExplosion),
  ("cd/multimediaexplosionshareware.tsv", MultiMediaEXPLOSIONShareware),
  ("cd/multimediagalerie.tsv", MultimediaGalerie),
  ("cd/multimedialacompil2.tsv", MultimediaLaCompil2),
  ("cd/multimediamegahits1.tsv", MultiMediaMegahits1),
  ("cd/multimediamusicbox.tsv", MultimediaMusicbox),
  ("cd/multimediaplus.tsv", MultimediaPlus),
  ("cd/multimediasoundfactory.tsv", MultimediaSoundFactory),
  ("cd/multimediatoolkitps.tsv", MultimediaToolkitPS),
  ("cd/music95.tsv", Music95),
  ("cd/musicbox1994.tsv", MusicBox1994),
  ("cd/musicboxpc.tsv", MusicBoxPC),
  ("cd/musicmodsoundeffect.tsv", MusicModSoundEffect),
  ("cd/musicwin952.tsv", MusicWin952),
  ("cd/networkcd1.tsv", NetworkCD1),
  ("cd/networkcd2.tsv", NetworkCD2),
  ("cd/newsflash1.tsv", Newsflash1),
  ("cd/newsflash2.tsv", Newsflash2),
  ("cd/nightshiftsoundvision.tsv", NightshiftSoundVision),
  ("cd/octamed6.tsv", Octamed6),
  ("cd/octamedssv1.tsv", OctaMEDSSv1),
  ("cd/otherware.tsv", Otherware),
  ("cd/pcconsument2mar95.tsv", PCConsument2Mar95),
  ("cd/pcmagazinecover.tsv", PCMagazineCover),
  ("cd/pdshareware14000.tsv", PDShareware14000),
  ("cd/perseus.tsv", Perseus),
  ("cd/phoenix3.tsv", Phoenix3),
  ("cd/phoenix4.tsv", Phoenix4),
  ("cd/phoenix5.tsv", Phoenix5),
  ("cd/plex1.tsv", Plex1),
  ("cd/plex2.tsv", Plex2),
  ("cd/plex3.tsv", Plex3),
  ("cd/plex4.tsv", Plex4),
  ("cd/plex5.tsv", Plex5),
  ("cd/plex6.tsv", Plex6),
  ("cd/powermodul1.tsv", PowerModul1),
  ("cd/powermodul2.tsv", PowerModul2),
  ("cd/poweron.tsv", PowerOn),
  ("cd/primashareware3.tsv", PrimaShareware3),
  ("cd/redhotshareware93.tsv", RedHotShareware93),
  ("cd/resourcelibmultimedia.tsv", ResourceLibMultimedia),
  ("cd/scenaplexe.tsv", ScenaPLEXE),
  ("cd/scene96.tsv", Scene96),
  ("cd/scenereleases8095.tsv", SceneReleases8095),
  ("cd/scenestorm.tsv", SceneStorm),
  ("cd/scenexplorer.tsv", SceneXplorer),
  ("cd/scenexplorer2.tsv", SceneXplorer2),
  ("cd/scifisensationv2.tsv", SciFiSensationv2),
  ("cd/sharewareextravaganza.tsv", SharewareExtravaganza),
  ("cd/sharewareuniversegold.tsv", SharewareUniverseGold),
  ("cd/sightssounds.tsv", SightsSounds),
  ("cd/software2000.tsv", Software2000),
  ("cd/softwareexplosion.tsv", SoftwareExplosion),
  ("cd/somuchshareware1.tsv", SoMuchShareware1),
  ("cd/somuchshareware2.tsv", SoMuchShareware2),
  ("cd/somuchshareware3.tsv", SoMuchShareware3),
  ("cd/somuchshareware5.tsv", SoMuchShareware5),
  ("cd/sound1.tsv", Sound1),
  ("cd/soundblaster17.tsv", Soundblaster17),
  ("cd/soundblastermultimedia3.tsv", SoundblasterMultiMedia3),
  ("cd/soundblastermultimedia4.tsv", SoundblasterMultiMedia4),
  ("cd/soundcollection.tsv", SoundCollection),
  ("cd/soundmod1.tsv", SoundMod1),
  ("cd/soundmod2.tsv", SoundMod2),
  ("cd/soundmusicmidicollection2.tsv", SoundMusicMidiCollection2),
  ("cd/sounds1996.tsv", Sounds1996),
  ("cd/soundsoftware.tsv", SoundSoftware),
  ("cd/soundsterrific.tsv", SoundsTerrific),
  ("cd/soundsterrificii.tsv", SoundsTerrificII),
  ("cd/soundstudio.tsv", SoundStudio),
  ("cd/soundwarecollection.tsv", SoundwareCollection),
  ("cd/spacelib1.tsv", SPACELib1),
  ("cd/tcedemo2.tsv", TCEDemo2),
  ("cd/tekno51996.tsv", TEKNO51996),
  ("cd/tekno61996.tsv", TEKNO61996),
  ("cd/tekno11997.tsv", TEKNO11997),
  ("cd/tekno41997.tsv", TEKNO41997),
  ("cd/tekno1998musicmania.tsv", TEKNO1998MusicMania),
  ("cd/terrasoundlibrary.tsv", TerraSoundLibrary),
  ("cd/themodulecollection.tsv", TheModuleCollection),
  ("cd/thesoundlibrary.tsv", TheSoundLibrary),
  ("cd/thesoundsite.tsv", TheSoundSite),
  ("cd/theultimatemusicsound1.tsv", TheUltimateMusicSound1),
  ("cd/theultimatemusicsound2.tsv", TheUltimateMusicSound2),
  ("cd/toolsunlimitedblanker.tsv", ToolsUnlimitedBlanker),
  ("cd/ugamodcollection1.tsv", UgamodCollection1),
  ("cd/ugamodcollection2.tsv", UgamodCollection2),
  ("cd/ultrasounds.tsv", Ultrasounds),
  ("cd/unitedpdgold.tsv", UnitedPDGold),
  ("cd/universinteractif.tsv", UniversInteractif),
  ("cd/utilitiespro1500.tsv", UtilitiesPro1500),
  ("cd/vgaspectrum.tsv", VGASpectrum),
  ("cd/vgaspectrum2.tsv", VGASpectrum2),
  ("cd/vrtulnik1.tsv", Vrtulnik1),
  ("cd/vrtulnik2.tsv", Vrtulnik2),
  ("cd/vrtulnik3.tsv", Vrtulnik3),
  ("cd/weirdsciencemultimedia.tsv", WeirdScienceMultimedia),
  ("cd/weirdsciencemultimedia2.tsv", WeirdScienceMultimedia2),
  ("cd/whitelinetransmission.tsv", WhitelineTransmission),
  ("cd/workbenchaddon.tsv", WorkbenchAddOn),
  ("cd/worldofa1200.tsv", WorldOfA1200),
  ("cd/worldofamiga.tsv", WorldOfAmiga),
  ("cd/worldofshareware.tsv", WorldOfShareware),
  ("cd/worldofsound1.tsv", WorldOfSound1),
  ("cd/worldofsound2.tsv", WorldOfSound2),
  ("collection/1996mods.tsv", _1996Mods),
  ("collection/accug.tsv", ACCUG),
  ("collection/alteredperception.tsv", AlteredPerception),
  ("collection/ambmod.tsv", AmbMod),
  ("collection/amiganuts.tsv", AmigaNuts),
  ("collection/aolfilelibrary.tsv", AOLFileLibrary),
  ("collection/celicmodules.tsv", CelicModules),
  ("collection/deck.tsv", Deck),
  ("collection/demonhellraiser.tsv", DemonHellraiser),
  ("collection/dfxcollection.tsv", DfxCollection),
  ("collection/espritdeapplecorps.tsv", EspritDeAppleCorps),
  ("collection/fredthegang2014.tsv", FredTheGang2014),
  ("collection/jbb.tsv", JBB),
  ("collection/keygenmusicpack202003.tsv", KeygenMusicPack202003),
  ("collection/lemonamiga.tsv", LemonAmiga),
  ("collection/melcom.tsv", Melcom),
  ("collection/metinseven.tsv", MetinSeven),
  ("collection/mod_jp.tsv", ModJP),
  ("collection/modulesinjp.tsv", ModulesInJP),
  ("collection/modulypl.tsv", ModulyPL),
  ("collection/mrgreat.tsv", MrGreat),
  ("collection/mroherd.tsv", MrOherd),
  ("collection/playitbyyear.tsv", PlayItByYear),
  ("collection/protrackermodulesgpack.tsv", ProTrackerModulesGPack),
  ("collection/retroplaywhdloadpacks.tsv", RetroPlayWHDLoadPacks),
  ("collection/scenecat.tsv", SceneCat),
  ("collection/sonixcd.tsv", SonixCD),
  ("collection/tcdgamemods.tsv", TCDGameMods),
  ("collection/terrygreenpd.tsv", TerryGreenPD),
  ("collection/thescenearchives.tsv", TheSceneArchives),
  ("collection/theultimatemodcollection.tsv", TheUltimateModCollection),
  ("collection/tosecmusic.tsv", TOSECMusic),
  ("collection/tosecmusic_unknown.tsv", TOSECMusicUnknown),
  ("collection/tundrah.tsv", Tundrah),
  ("collection/unnamed.tsv", Unnamed),
  ("collection/wantedteamdattapes.tsv", WantedTeamDATTapes),
  ("group/chillproductions.tsv", ChillProductions),
  ("group/dajormas.tsv", DaJormas),
  ("group/kosmic.tsv", Kosmic),
  ("group/modsoulbrother.tsv", ModSoulBrother),
  ("group/netlabelarchive.tsv", NetlabelArchive),
  ("group/noisemusic.tsv", NoiseMusic),
  ("site/amegas.tsv", Amegas),
  ("site/amigamega_demos.tsv", AmigaMegaDemos),
  ("site/amigamega_games.tsv", AmigaMegaGames),
  ("site/amigamodulesfreefr.tsv", AmigaModulesFreeFr),
  ("site/amigamuseum.tsv", AmigaMuseum),
  ("site/amigamusiccollection.tsv", AmigaMusicCollection),
  ("site/amigascne.tsv", AmigaScne),
  ("site/aminet.tsv", Aminet),
  ("site/amisectorone.tsv", AmiSectorOne),
  ("site/amp.tsv", AMP),
  ("site/arcadedemoncouk.tsv", ArcadeDemonCoUK),
  ("site/artpacksacidorg.tsv", ArtPacksAcidOrg),
  ("site/artscene.tsv", ArtScene),
  ("site/atariftp.tsv", AtariFTP),
  ("site/chiptuneapp.tsv", ChiptuneApp),
  ("site/chiptunecom.tsv", ChiptuneCom),
  ("site/classicgamesoundtracks.tsv", ClassicGameSoundtracks),
  ("site/demodulate.tsv", Demodulate),
  ("site/demozoo_music_leftovers.tsv", DemozooMusicLeftovers),
  ("site/demozoo_prod_leftovers.tsv", DemozooProdLeftovers),
  ("site/dim13.tsv", Dim13),
  ("site/flerp.tsv", Flerp),
  ("site/ftpkloszartpl.tsv", FTPKloszArtPL),
  ("site/fujiology.tsv", Fujiology),
  ("site/funet.tsv", Funet),
  ("site/hackedamigamusic.tsv", HackedAmigaMusic),
  ("site/haxorfi.tsv", Haxorfi),
  ("site/hobbes.tsv", Hobbes),
  ("site/hornet.tsv", Hornet),
  ("site/jpvscenereleases.tsv", jPVSceneReleases),
  ("site/majaradio.tsv", MajaRadio),
  ("site/modarchive.tsv", ModArchive),
  ("site/modland.tsv", Modland),
  ("site/modland_favourites.tsv", ModlandFavourites),
  ("site/modland_incoming.tsv", ModlandIncoming),
  ("site/modland_software.tsv", ModlandSoftware),
  ("site/modulespl.tsv", ModulesPL),
  ("site/nostalgicplayer.tsv", NostalgicPlayer),
  ("site/oldexotica.tsv", OldExotica),
  ("site/retroexo.tsv", RetroExo),
  ("site/sceneorg.tsv", SceneOrg),
  ("site/sceneorg_lostfound.tsv", SceneOrgLostFound),
  ("site/scenesporg.tsv", SceneSporg),
  ("site/sembiance.tsv", Sembiance),
  ("site/soamc.tsv", SOAMC),
  ("site/sxiiikeygenmusic.tsv", SXIIIKeygenMusic),
  ("site/thebbsorgarchive.tsv", TheBBSOrgArchive),
  ("site/unexotica.tsv", UnExotica),
  ("site/wantedteam.tsv", WantedTeam),
  ("site/worldofgamemods.tsv", WorldOfGameMods),
  ("site/zakalwe.tsv", Zakalwe),
);

final case class TsvEntry (
  md5: String,
  subsong: Int,
  songlength: Int,
  songend: String,
  player: String,
  format: String,
  channels: Int,
  filesize: Int,
  xxh32: String,
  crc32: String,
  path: String,
)

lazy val tsvs = tsvfiles.par.map(tsv => (tsv._2, Using(scala.io.Source.fromFile(s"sources/${tsv._1}")(using scala.io.Codec.UTF8))(tsv =>
  var player = ""
  tsv.getLines().map(line =>
    val l = line.split("\t")
    if (l.length > 4) {
      player = l(4)
      TsvEntry(l(0), l(1).toInt, l(2).toInt, l(3), player, l(5), if (l(6).isEmpty) 0 else l(6).toInt, l(7).toInt, l(8), l(9), l(10))
    } else TsvEntry(l(0), l(1).toInt, l(2).toInt, l(3), player, "", 0, -1, "", "", "")
  ).toBuffer
).get.sortBy(e => (e.md5, e.subsong)).groupBy(_.md5))).seq

final case class SourceDBEntry (
  md5: String,
  path: String,
  filesize: Int,
  xxh32: String,
  crc32: String
)

def readSourceDB(source: Source) = {
  tsvs.filter(_._1 == source).par.flatMap(_._2).map({case (md5,subsongs) =>
    /*
    if (subsongs.groupBy(_.subsong).exists(_._2.size > 1)) {
      System.err.println("DEBUG: duplicate files in " + source + " for " + md5 + ": " + subsongs)
    }
    */
    subsongs.filter(_.path != "").map(e =>
      SourceDBEntry(md5, e.path, e.filesize, e.xxh32, e.crc32)
    )
  }).flatten.seq
}.toSeq

val sourceDB = Source.values.filter(_ != Source.NONE).par.map(s => (s, readSourceDB(s))).seq.toMap
val by_crc32_filesize = sourceDB.values.flatten.groupBy(e => (e.crc32, e.filesize))
by_crc32_filesize.foreach(group => {
  if (group._2.size > 1 && group._2.exists(_.md5 != group._2.head.md5)) {
    System.err.println("WARN: duplicate files in sourceDB for crc32 " + group._1._1 + " and filesize " + group._1._2 + ": " + group._2)
  }
})

val yearPattern1 = """\/(\d{4})\/""".r
val yearPattern2 = """^(\d{4})[\/|\.]""".r
val yearPattern3 = """[ \)]\((\d{4})\)[\.\/\(]""".r
val yearPattern4 = """\((\d{4})-\d{2}-\d{2}\)""".r
val yearRangePattern1 = """[\/|^](\d{4})-(\d{4})\/""".r
val yearRangePattern2 = """[\/](\d{4})-(\d{2})\/""".r
val blacklist = Map(
  ChiptuneApp -> Set("Game Mods/"),
  Hornet -> Set("music/songs/1995/a/agenda.zip","music/songs/1995/p/palli.zip","music/songs/1995/w/wierdtow.zip"),
  LemonAmiga -> Set("1987/"),
  NostalgicPlayer -> Set("format/MED210MMD0.zip/MED 2.10 (MMD0)/1990/"),
  PlayItByYear -> Set(
    "1986.zip/ADF/_misc/",
    "1987.zip/ADF/_misc/",
    "1988.zip/ADF/_misc/",
    "1989.zip/ADF/_misc/",
    "1990.zip/ADF/_misc/",
    "1991.zip/ADF/_misc/",
    "1992.zip/ADF/_misc/",
    "1993.zip/ADF/_misc/",
    "1994.zip/ADF/_misc/",
    "1995.zip/ADF/_misc/",
    "1995.zip/ADF/_misc/",
  ),
  RetroExo -> Set(
    "exodos/Arcade Trivia Quiz (1989).zip",
    "exodos/Crazy Sue (1990).zip",
    "exodos/CD-Man Version 2.0 (1989).zip",
  ),
  SceneReleases8095 -> Set(
    "1990/CD_Man_2-DPS.zip"
  ),
  TOSECMusic -> Set(),
  TOSECMusicUnknown -> Set()
)
val _sourceYears = tsvs.par.flatMap({case (source, entries) =>
  if (!blacklist.contains(source) || blacklist(source).nonEmpty) {
    val blacklistedPaths = blacklist.getOrElse(source, Set.empty)
    entries.flatMap({case (md5, subsongs) =>
      subsongs
      .filter(e => e.path != "" && !blacklistedPaths.exists(e.path.startsWith))
      .flatMap(e => {
        val path = e.path
        lazy val year1 = yearPattern1.findFirstMatchIn(path).map(_.group(1)).getOrElse("").toIntOption.getOrElse(0)
        lazy val year2 = yearPattern2.findFirstMatchIn(path).map(_.group(1)).getOrElse("").toIntOption.getOrElse(0)
        lazy val year3 = yearPattern3.findFirstMatchIn(path).map(_.group(1)).getOrElse("").toIntOption.getOrElse(0)
        lazy val year4 = yearPattern4.findFirstMatchIn(path).map(_.group(1)).getOrElse("").toIntOption.getOrElse(0)
        if (year1 >= 1985 && year1 <= 2026) {
          Some(md5, year1, source, path)
        } else if (year2 >= 1985 && year2 <= 2026) {
          Some(md5, year2, source, path)
        } else if (year3 >= 1985 && year3 <= 2026) {
          Some(md5, year3, source, path)
        } else if (year4 >= 1985 && year4 <= 2026) {
          Some(md5, year4, source, path)
        } else None
      })
    })
  } else Seq.empty
})

val _sourceYears2 = tsvs.par.flatMap({case (source, entries) =>
  if (!blacklist.contains(source) || blacklist(source).nonEmpty) {
    val blacklistedPaths = blacklist.getOrElse(source, Set.empty)
    entries.flatMap({case (md5, subsongs) =>
      subsongs
      .filter(e => e.path != "" && !blacklistedPaths.exists(e.path.startsWith))
      .flatMap(e => {
        val path = e.path
        lazy val yearRange1 = yearRangePattern1.findFirstMatchIn(path).map(m => (m.group(1).toInt, m.group(2).toInt))
        lazy val yearRange2 = yearRangePattern2.findFirstMatchIn(path).map(m => (m.group(1).toInt, m.group(2).toInt))
        if (yearRange1.isDefined) {
          val (start, end) = yearRange1.get
          if (start >= 1985 && end <= 2026 && start < end) {
            Some(md5, end, source, path)
          } else {
            None
          }
        } else if (yearRange2.isDefined) {
          val (start, end) = yearRange2.get
          if (start >= 1985 && start < 2000 && end >= 85 && end <= 99) {
            Some(md5, 1900 + end.toInt, source, path)
          } else if (start >= 2000 && start <= 2026 && end >= 0 && end <= 26) {
            Some(md5, 2000 + end.toInt, source, path)
          } else {
            None
          }
        } else None  
      })
    })
  } else Seq.empty
})

val sourceYearConstraints = (_sourceYears ++ _sourceYears2).groupBy(_._1).mapValues(_.map(t => (t._2, t._3, t._4)).minBy(_._1)).map({case (md5, (year, source, _)) =>
  md5.take(12) -> (year, source)
}).seq

val blacklist2 = Map(
  Funet -> Set("amiga/audio/modules/med/199","amiga/audio/modules/misc/199"),
  Hornet -> Set("music/songs/","tla/songs/","music/disks/")
)
val sourcePathYears = _sourceYears.groupBy(_._1).mapValues(_.map(t => (t._2, t._3, t._4)).minBy(_._1)).flatMap({case (md5, (year, source, path)) =>
  if (blacklist2.contains(source) && blacklist2(source).exists(path.startsWith)) {
    None
  } else
    Some(MetaData(hash = md5.take(12), authors = Buffer.empty, publishers = Buffer.empty, album = "", year = year))
}).seq.toBuffer.distinct

lazy val amp_by_path = sourceDB(Source.AMP).groupBy(_.path.toLowerCase)
lazy val modland_by_path = sourceDB(Source.Modland).groupBy(_.path.toLowerCase)
lazy val unexotica_by_path = sourceDB(Source.UnExotica).groupBy(_.path.split("/").take(3).mkString("/").toLowerCase)
lazy val wantedteam_by_path = sourceDB(Source.WantedTeam).groupBy(_.path.split("/").take(2).mkString("/").toLowerCase)
lazy val amigascne_by_path = sourceDB(Source.AmigaScne).groupBy(_.path.toLowerCase)

def findArchive(archivePath: String, paths: Map[String, Seq[SourceDBEntry]]) = {
  var entries = Buffer.empty[SourceDBEntry]
  val iter = paths.iterator
  while (iter.hasNext) {
    val (k, v) = iter.next()
    if (k.startsWith(archivePath+"/")) {
      entries ++= v
    }
  }
  if (entries.isEmpty) {
    Buffer.empty[(String, String)]
  } else {
    entries.map(e => (e.md5, e.path)).distinct
  }
}
